# Generated by Django 5.0.6 on 2024-08-31 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
