# Generated by Django 5.0.6 on 2024-09-01 09:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_courses_category_delete_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='date_of_start',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of start'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='description',
            field=models.TextField(default='Description', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='language',
            field=models.TextField(default='Language in which courses are conducted', verbose_name='Languages'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='month',
            field=models.IntegerField(default=0, verbose_name='Amount of months'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Price per month'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Name of course'),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('datetime_create', models.DateTimeField(auto_now=True)),
                ('auth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.courses')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='catalog.comments')),
            ],
        ),
    ]
